# backend/auth-service/docker-compose.yml
version: '3.8'

services:
  # PostgreSQL Database
  postgres-auth:
    image: postgres:15-alpine
    container_name: ev_auth_postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - ev_network

  # Redis
  redis-auth:
    image: redis:7-alpine
    container_name: ev_auth_redis
    ports:
      - "6379:6379"
    networks:
      - ev_network

  # Auth Service
  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ev_auth_service
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: development
      PORT: 3001
      DB_HOST: postgres-auth
      DB_NAME: auth_db
      DB_USER: postgres
      DB_PASSWORD: postgres123
      REDIS_URL: redis://redis-auth:6379
      JWT_SECRET: your_jwt_secret_here
      JWT_REFRESH_SECRET: your_refresh_secret_here
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres-auth
      - redis-auth
    networks:
      - ev_network

networks:
  ev_network:
    driver: bridge

volumes:
  postgres_auth_data: